// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PBDASHBOARD.Data;

namespace PBDASHBOARD.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Contributor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CristinPersonId")
                        .HasColumnType("text");

                    b.Property<int?>("FacultyId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("SurName")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("Contributors");
                });

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.DeviceFlowCodes", b =>
                {
                    b.Property<string>("UserCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("Expiration")
                        .IsRequired()
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("UserCode");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.HasIndex("Expiration");

                    b.ToTable("DeviceCodes");
                });

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.PersistedGrant", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)");

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Key");

                    b.HasIndex("Expiration");

                    b.HasIndex("SubjectId", "ClientId", "Type");

                    b.ToTable("PersistedGrants");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("PBDASHBOARD.Data.CustomRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("PBDASHBOARD.Models.AssociationModels.Affiliation", b =>
                {
                    b.Property<int>("ContributorId")
                        .HasColumnType("integer");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("integer");

                    b.HasKey("ContributorId", "InstitutionId");

                    b.HasIndex("InstitutionId");

                    b.ToTable("Affiliations");
                });

            modelBuilder.Entity("PBDASHBOARD.Models.AssociationModels.ContributorReGroup", b =>
                {
                    b.Property<int>("ResearchGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("ContributorId")
                        .HasColumnType("integer");

                    b.HasKey("ResearchGroupId", "ContributorId");

                    b.HasIndex("ContributorId");

                    b.ToTable("ContributorReGroups");
                });

            modelBuilder.Entity("PBDASHBOARD.Models.AssociationModels.InstituteResearchProject", b =>
                {
                    b.Property<int>("InstituteId")
                        .HasColumnType("integer");

                    b.Property<int>("ResearchProjectId")
                        .HasColumnType("integer");

                    b.HasKey("InstituteId", "ResearchProjectId");

                    b.HasIndex("ResearchProjectId");

                    b.ToTable("InstituteResearchProjects");
                });

            modelBuilder.Entity("PBDASHBOARD.Models.AssociationModels.PublicationContributor", b =>
                {
                    b.Property<int>("ContributorId")
                        .HasColumnType("integer");

                    b.Property<int>("PublicationId")
                        .HasColumnType("integer");

                    b.Property<int?>("AffiliationContributorId")
                        .HasColumnType("integer");

                    b.Property<int?>("AffiliationInstitutionId")
                        .HasColumnType("integer");

                    b.HasKey("ContributorId", "PublicationId");

                    b.HasIndex("PublicationId");

                    b.HasIndex("AffiliationContributorId", "AffiliationInstitutionId");

                    b.ToTable("PublicationContributors");
                });

            modelBuilder.Entity("PBDASHBOARD.Models.AssociationModels.PublicationInstitute", b =>
                {
                    b.Property<int>("PublicationId")
                        .HasColumnType("integer");

                    b.Property<int>("InstituteId")
                        .HasColumnType("integer");

                    b.HasKey("PublicationId", "InstituteId");

                    b.HasIndex("InstituteId");

                    b.ToTable("PublicationInstitutes");
                });

            modelBuilder.Entity("PBDASHBOARD.Models.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<int>("NameId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("NameId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("PBDASHBOARD.Models.CurrentReGroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("PBDASHBOARD.Models.Faculty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CristinUnitId")
                        .HasColumnType("text");

                    b.Property<int?>("InstitutionId")
                        .HasColumnType("integer");

                    b.Property<int>("NameId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("NameId");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("PBDASHBOARD.Models.Institute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CristinUnitId")
                        .HasColumnType("text");

                    b.Property<int>("FacultyId")
                        .HasColumnType("integer");

                    b.Property<int>("NameId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer");

                    b.Property<string>("url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.HasIndex("NameId");

                    b.ToTable("Institutes");
                });

            modelBuilder.Entity("PBDASHBOARD.Models.Institution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Acronym")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("CristinUnitId")
                        .HasColumnType("text");

                    b.Property<int?>("InstitutionNameid")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionNameid");

                    b.ToTable("Institutions");
                });

            modelBuilder.Entity("PBDASHBOARD.Models.Name", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("En")
                        .HasColumnType("text");

                    b.Property<string>("Nb")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Names");
                });

            modelBuilder.Entity("PBDASHBOARD.Models.Publication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("Categoryid")
                        .HasColumnType("integer");

                    b.Property<string>("CristinId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DatePublished")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<string>("YearPublished")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Categoryid");

                    b.ToTable("Publications");
                });

            modelBuilder.Entity("PBDASHBOARD.Models.ResearchGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("AdminId")
                        .HasColumnType("integer");

                    b.Property<string>("GroupName")
                        .HasColumnType("text");

                    b.Property<string>("GroupUrl")
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("ResearchGroups");
                });

            modelBuilder.Entity("PBDASHBOARD.Models.ResearchGroupCurrentMembers", b =>
                {
                    b.Property<int>("ResearchGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentReGroupMemberId")
                        .HasColumnType("integer");

                    b.Property<string>("MemberRole")
                        .HasColumnType("text");

                    b.Property<bool>("RoleStatus")
                        .HasColumnType("boolean");

                    b.HasKey("ResearchGroupId", "CurrentReGroupMemberId");

                    b.HasIndex("CurrentReGroupMemberId");

                    b.ToTable("CurrentGroupMembers");
                });

            modelBuilder.Entity("PBDASHBOARD.Models.ResearchProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CristinProjectId")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Titleid")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Titleid");

                    b.ToTable("ResearchProjects");
                });

            modelBuilder.Entity("PBDASHBOARD.Models.SynchronisationDate", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("lasSyncYear")
                        .HasColumnType("text");

                    b.Property<bool>("runOnce")
                        .HasColumnType("boolean");

                    b.Property<string>("startYear")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("syncDate");
                });

            modelBuilder.Entity("Contributor", b =>
                {
                    b.HasOne("PBDASHBOARD.Models.Faculty", null)
                        .WithMany("Researchers")
                        .HasForeignKey("FacultyId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("PBDASHBOARD.Data.CustomRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("PBDASHBOARD.Models.CurrentReGroupMember", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("PBDASHBOARD.Models.CurrentReGroupMember", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("PBDASHBOARD.Data.CustomRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PBDASHBOARD.Models.CurrentReGroupMember", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("PBDASHBOARD.Models.CurrentReGroupMember", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PBDASHBOARD.Models.AssociationModels.Affiliation", b =>
                {
                    b.HasOne("Contributor", "Contributor")
                        .WithMany("Affiliations")
                        .HasForeignKey("ContributorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PBDASHBOARD.Models.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contributor");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("PBDASHBOARD.Models.AssociationModels.ContributorReGroup", b =>
                {
                    b.HasOne("Contributor", "Contributor")
                        .WithMany("Groups")
                        .HasForeignKey("ContributorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PBDASHBOARD.Models.ResearchGroup", "ResearchGroup")
                        .WithMany("GroupMembers")
                        .HasForeignKey("ResearchGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contributor");

                    b.Navigation("ResearchGroup");
                });

            modelBuilder.Entity("PBDASHBOARD.Models.AssociationModels.InstituteResearchProject", b =>
                {
                    b.HasOne("PBDASHBOARD.Models.Institute", "Institute")
                        .WithMany("InstituteResearchProjects")
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PBDASHBOARD.Models.ResearchProject", "ResearchProject")
                        .WithMany()
                        .HasForeignKey("ResearchProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institute");

                    b.Navigation("ResearchProject");
                });

            modelBuilder.Entity("PBDASHBOARD.Models.AssociationModels.PublicationContributor", b =>
                {
                    b.HasOne("Contributor", "Contributor")
                        .WithMany("ContributorPublications")
                        .HasForeignKey("ContributorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PBDASHBOARD.Models.Publication", "Publication")
                        .WithMany("Contributors")
                        .HasForeignKey("PublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PBDASHBOARD.Models.AssociationModels.Affiliation", "Affiliation")
                        .WithMany()
                        .HasForeignKey("AffiliationContributorId", "AffiliationInstitutionId");

                    b.Navigation("Affiliation");

                    b.Navigation("Contributor");

                    b.Navigation("Publication");
                });

            modelBuilder.Entity("PBDASHBOARD.Models.AssociationModels.PublicationInstitute", b =>
                {
                    b.HasOne("PBDASHBOARD.Models.Institute", "Institute")
                        .WithMany("PublicationInstitutes")
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PBDASHBOARD.Models.Publication", "Publication")
                        .WithMany("Institutes")
                        .HasForeignKey("PublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institute");

                    b.Navigation("Publication");
                });

            modelBuilder.Entity("PBDASHBOARD.Models.Category", b =>
                {
                    b.HasOne("PBDASHBOARD.Models.Name", "Name")
                        .WithMany()
                        .HasForeignKey("NameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Name");
                });

            modelBuilder.Entity("PBDASHBOARD.Models.Faculty", b =>
                {
                    b.HasOne("PBDASHBOARD.Models.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId");

                    b.HasOne("PBDASHBOARD.Models.Name", "UnitName")
                        .WithMany()
                        .HasForeignKey("NameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institution");

                    b.Navigation("UnitName");
                });

            modelBuilder.Entity("PBDASHBOARD.Models.Institute", b =>
                {
                    b.HasOne("PBDASHBOARD.Models.Faculty", "Faculty")
                        .WithMany("Institutes")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PBDASHBOARD.Models.Name", "UnitName")
                        .WithMany()
                        .HasForeignKey("NameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("UnitName");
                });

            modelBuilder.Entity("PBDASHBOARD.Models.Institution", b =>
                {
                    b.HasOne("PBDASHBOARD.Models.Name", "InstitutionName")
                        .WithMany()
                        .HasForeignKey("InstitutionNameid");

                    b.Navigation("InstitutionName");
                });

            modelBuilder.Entity("PBDASHBOARD.Models.Publication", b =>
                {
                    b.HasOne("PBDASHBOARD.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("Categoryid");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PBDASHBOARD.Models.ResearchGroup", b =>
                {
                    b.HasOne("PBDASHBOARD.Models.CurrentReGroupMember", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId");

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("PBDASHBOARD.Models.ResearchGroupCurrentMembers", b =>
                {
                    b.HasOne("PBDASHBOARD.Models.CurrentReGroupMember", "_member")
                        .WithMany("CurrentGroupMembers")
                        .HasForeignKey("CurrentReGroupMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PBDASHBOARD.Models.ResearchGroup", "ResearchGroup")
                        .WithMany("CurrentGroupMembers")
                        .HasForeignKey("ResearchGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_member");

                    b.Navigation("ResearchGroup");
                });

            modelBuilder.Entity("PBDASHBOARD.Models.ResearchProject", b =>
                {
                    b.HasOne("PBDASHBOARD.Models.Name", "Title")
                        .WithMany()
                        .HasForeignKey("Titleid");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Contributor", b =>
                {
                    b.Navigation("Affiliations");

                    b.Navigation("ContributorPublications");

                    b.Navigation("Groups");
                });

            modelBuilder.Entity("PBDASHBOARD.Models.CurrentReGroupMember", b =>
                {
                    b.Navigation("CurrentGroupMembers");
                });

            modelBuilder.Entity("PBDASHBOARD.Models.Faculty", b =>
                {
                    b.Navigation("Institutes");

                    b.Navigation("Researchers");
                });

            modelBuilder.Entity("PBDASHBOARD.Models.Institute", b =>
                {
                    b.Navigation("InstituteResearchProjects");

                    b.Navigation("PublicationInstitutes");
                });

            modelBuilder.Entity("PBDASHBOARD.Models.Publication", b =>
                {
                    b.Navigation("Contributors");

                    b.Navigation("Institutes");
                });

            modelBuilder.Entity("PBDASHBOARD.Models.ResearchGroup", b =>
                {
                    b.Navigation("CurrentGroupMembers");

                    b.Navigation("GroupMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
